from linked_list import LinkedList

my_list = LinkedList()
my_list.append(2)
my_list.append(4)
my_list.append(8)
my_list.append(16)
my_list.append(32)

my_list.show()
my_list.length()
my_list.push_front(0)
my_list.show()
my_list.remove_back()
my_list.show()
my_list.remove_front()
my_list.show()
my_list.value_at(0)
my_list.insert(5, 3)
my_list.show()
my_list.reverse()
my_list.show()